source "https://rubygems.org"

ruby "2.5.1"

gem "rails", "~> 5.0.2"
gem "sqlite3"
gem "better_errors"
gem "dotenv-rails"
gem "sidekiq"
gem "devise_token_auth"
gem "resque"
gem "resque-status"
gem "nokogiri", "1.6.8.1"
gem "mina"
gem "puma"
gem "redis", "<4"
gem "rack-cors"